version: '3.8'

services:
  skwaq:
    build:
      context: .
      target: development
    volumes:
      - .:/app
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=skwaqdev
      - PYTHONPATH=/app
    depends_on:
      - neo4j
    command: sleep infinity  # Keep container running for development

  neo4j:
    image: neo4j:5.15.0
    environment:
      - NEO4J_AUTH=neo4j/skwaqdev
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=2G
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins: