#!/usr/bin/env python3
"""Generate the BinPool ground-truth manifest from upstream binpool_info.json."""

from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.request
from pathlib import Path

DEFAULT_SOURCE_URL = (
    "https://raw.githubusercontent.com/SimaArasteh/binpool/main/binpool_info.json"
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, help="Local binpool_info.json path")
    parser.add_argument(
        "--source-url",
        default=DEFAULT_SOURCE_URL,
        help="Remote binpool_info.json URL when --input is not provided",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("data/gym/ground_truth/binpool.toml"),
        help="Where to write the generated manifest",
    )
    parser.add_argument(
        "--version",
        default="binpool-info-json-main",
        help="Version string to embed in the manifest",
    )
    return parser.parse_args()


def load_metadata(args: argparse.Namespace) -> dict[str, object]:
    if args.input:
        return json.loads(args.input.read_text(encoding="utf-8"))

    with urllib.request.urlopen(args.source_url) as response:
        return json.load(response)


def parse_cwes(values: list[object]) -> list[int]:
    cwes: list[int] = []
    for value in values:
        text = str(value).strip()
        match = re.search(r"(\d+)$", text)
        if not match:
            continue
        number = int(match.group(1))
        if number > 0 and number not in cwes:
            cwes.append(number)
    return cwes


def toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def choose_case_path(binary_path: str, file_func: object) -> str:
    if isinstance(file_func, dict):
        for candidate in file_func:
            if isinstance(candidate, str) and candidate and ".." not in candidate:
                return candidate
    return binary_path


def build_cases(metadata: dict[str, object]) -> tuple[list[dict[str, object]], dict[str, int]]:
    cases: list[dict[str, object]] = []
    skipped = {
        "no_binary": 0,
        "no_cwe": 0,
    }

    for cve_id in sorted(metadata):
        entry = metadata[cve_id]
        if not isinstance(entry, dict):
            continue

        binaries = entry.get("binaries") or []
        if not isinstance(binaries, list) or not binaries:
            skipped["no_binary"] += 1
            continue

        cwes = parse_cwes(entry.get("cwes") or [])
        if not cwes:
            skipped["no_cwe"] += 1
            continue

        binary_path = str(binaries[0])
        case_path = choose_case_path(binary_path, entry.get("file_func"))
        cases.append(
            {
                "id": cve_id,
                "path": case_path,
                "binary_path": binary_path,
                "expected_cwes": cwes,
                "is_negative": False,
                "language": "binary",
            }
        )

    return cases, skipped


def render_manifest(
    *,
    version: str,
    source_url: str,
    cases: list[dict[str, object]],
    skipped: dict[str, int],
) -> str:
    lines = [
        "# Generated by scripts/generate_binpool_manifest.py",
        f"# Source: {source_url}",
        "# One representative vulnerable binary per CVE is selected from upstream",
        "# binpool_info.json when that entry publishes at least one binary and one CWE.",
        f"# Cases: {len(cases)}",
        f"# Skipped entries without binaries: {skipped['no_binary']}",
        f"# Skipped entries without usable CWEs: {skipped['no_cwe']}",
        'suite = "binpool"',
        f"version = {toml_string(version)}",
        'download_url = ""',
        'download_sha256 = ""',
        "",
    ]

    for case in cases:
        lines.extend(
            [
                "[[cases]]",
                f"id = {toml_string(case['id'])}",
                f"path = {toml_string(case['path'])}",
                f"binary_path = {toml_string(case['binary_path'])}",
                "expected_cwes = [{}]".format(
                    ", ".join(str(cwe) for cwe in case["expected_cwes"])
                ),
                "is_negative = false",
                f"language = {toml_string(case['language'])}",
                "",
            ]
        )

    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    metadata = load_metadata(args)
    cases, skipped = build_cases(metadata)
    manifest = render_manifest(
        version=args.version,
        source_url=str(args.input) if args.input else args.source_url,
        cases=cases,
        skipped=skipped,
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(manifest, encoding="utf-8")
    print(
        f"Wrote {len(cases)} BinPool cases to {args.output} "
        f"(skipped {skipped['no_binary']} without binaries, {skipped['no_cwe']} without usable CWEs)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
